version: '3'
services:
  php:
    build:
      context: ./docker/conf/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ${PROJECT_ROOT}:/var/www
      - ~/.composer:/var/www/.composer
      - ./docker/conf/nginx/netsells.test.crt:/var/www/certs/netsells.test.crt
      - ./docker/conf/nginx/netsells.test.key:/var/www/certs/netsells.test.key
    depends_on:
      - mysql
      - redis
    network_mode: bridge
    links:
      - mysql
      - redis
      - mailcatcher
    environment:
      PHP_IDE_CONFIG: "serverName=${APP_URL}"

  web:
    build:
      context: ./
      dockerfile: ./docker/conf/nginx/Dockerfile
    volumes:
      - ${PROJECT_ROOT}:/var/www
      - ./docker/conf/nginx/netsells.test.crt:/etc/nginx/netsells.test.crt
      - ./docker/conf/nginx/netsells.test.key:/etc/nginx/netsells.test.key
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - php
      - mysql
      - redis
    network_mode: bridge
    links:
      - php

  mysql:
    image: library/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    network_mode: bridge
    security_opt:
      - seccomp:unconfined

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./docker/data/redis:/data
    network_mode: bridge

  mailcatcher:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    restart: unless-stopped
    volumes:
      - ../data/email:/home/mailhog/email
    network_mode: bridge
